use crate::app_error::AppError;
use crate::config::Config;
use axum::{
    extract::Path,
    http::{header, StatusCode},
    response::IntoResponse,
};

/// Serve a favicon by filename from the PVC-backed assets directory.
///
/// Path: GET /api/favicons/:filename
///
/// Filenames are generated by the worker (e.g. `feed_42.ico`) and the path is
/// stored in `feeds.favicon_url`. Only simple filenames (no separators) are
/// accepted to prevent path-traversal attacks.
pub async fn get_favicon(Path(filename): Path<String>) -> Result<impl IntoResponse, AppError> {
    // Reject any filename that contains path separators or parent-dir components.
    if filename.contains('/') || filename.contains('\\') || filename.contains("..") {
        return Err(AppError::bad_request("Invalid filename"));
    }

    // Only allow characters that are safe as filesystem names.
    if !filename
        .chars()
        .all(|c| c.is_alphanumeric() || c == '_' || c == '-' || c == '.')
    {
        return Err(AppError::bad_request("Invalid filename"));
    }

    let assets_path = &Config::get().assets_path;
    let path = std::path::Path::new(assets_path)
        .join("favicons")
        .join(&filename);

    let bytes = tokio::fs::read(&path)
        .await
        .map_err(|_| AppError::not_found("Favicon not found"))?;

    // Derive content-type from extension; default to image/x-icon.
    let content_type = match path.extension().and_then(|e| e.to_str()) {
        Some("png") => "image/png",
        Some("svg") => "image/svg+xml",
        Some("gif") => "image/gif",
        Some("webp") => "image/webp",
        _ => "image/x-icon",
    };

    Ok((
        StatusCode::OK,
        [
            (header::CONTENT_TYPE, content_type),
            (header::CACHE_CONTROL, "public, max-age=86400"),
        ],
        bytes,
    ))
}
