use kaleido::auth::openapi as auth_openapi;
use kaleido::glass::openapi as glass_openapi;
use kaleido::glass::SecurityAddon;
use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        auth_openapi::paths::register,
        auth_openapi::paths::login,
        auth_openapi::paths::current,
        auth_openapi::paths::refresh,
        auth_openapi::paths::logout,
        auth_openapi::paths::verify_email,
        auth_openapi::paths::resend_confirmation,
        auth_openapi::paths::forgot_password,
        auth_openapi::paths::reset_password,
        auth_openapi::paths::oauth_authorize,
        auth_openapi::paths::oauth_callback,
        glass_openapi::paths::public_flags,
        glass_openapi::paths::list_flags,
        glass_openapi::paths::update_flag,
        glass_openapi::paths::get_metrics,
        crate::controllers::feeds::list_feeds,
        crate::controllers::feeds::create_feed,
        crate::controllers::feeds::unsubscribe_feed,
        crate::controllers::feeds::rename_feed,
        crate::controllers::feeds::update_feed_view,
        crate::controllers::feeds::list_articles,
        crate::controllers::feeds::get_article,
        crate::controllers::feeds::mark_feed_read,
        crate::controllers::feeds::mark_article_read,
        crate::controllers::feeds::toggle_save_article,
        crate::controllers::feeds::reorder_feeds,
        crate::controllers::feeds::get_task_status,
        crate::controllers::feeds::list_fetch_history,
        crate::controllers::folders::list_folders,
        crate::controllers::folders::create_folder,
        crate::controllers::folders::delete_folder,
        crate::controllers::folders::rename_folder,
        crate::controllers::folders::assign_feed_to_folder,
        crate::controllers::folders::list_folder_articles,
        crate::controllers::admin::fix_unread_drift,
        crate::controllers::admin::fetch_missing_favicons,
        crate::controllers::admin::list_feeds,
        crate::controllers::admin::list_feed_fetch_history,
        crate::controllers::admin::update_feed,
        crate::controllers::admin::fetch_feed_now,
        crate::controllers::admin::app_metrics,
    ),
    components(
        schemas(
            auth_openapi::schemas::MessageResponse,
            auth_openapi::schemas::RegisterRequest,
            auth_openapi::schemas::RegisterResponse,
            auth_openapi::schemas::LoginRequest,
            auth_openapi::schemas::UserResponse,
            auth_openapi::schemas::ResendConfirmationRequest,
            auth_openapi::schemas::ForgotPasswordRequest,
            auth_openapi::schemas::ResetPasswordRequest,
            glass_openapi::schemas::PublicFlagResponse,
            glass_openapi::schemas::FeatureFlagResponse,
            glass_openapi::schemas::UpdateFlagRequest,
            glass_openapi::schemas::PaginatedResponse<glass_openapi::schemas::FeatureFlagResponse>,
            glass_openapi::schemas::PaginatedResponse<glass_openapi::schemas::PublicFlagResponse>,
            glass_openapi::schemas::SystemMetrics,
            kaleido::glass::data::pagination::PaginationParams,
            kaleido::glass::data::pagination::PaginatedResponse<crate::controllers::feeds::ArticleResponse>,
            kaleido::glass::data::pagination::PaginatedResponse<crate::controllers::feeds::FetchHistoryResponse>,
            crate::controllers::feeds::CreateFeedRequest,
            crate::controllers::feeds::ReorderFeedItem,
            crate::controllers::feeds::UpdateFeedNameRequest,
            crate::controllers::feeds::UpdateFeedViewRequest,
            crate::controllers::feeds::FeedResponse,
            crate::controllers::feeds::ArticleResponse,
            crate::controllers::feeds::FetchHistoryResponse,
            crate::controllers::feeds::MessageResponse,
            crate::controllers::feeds::CreateFeedResponse,
            crate::controllers::feeds::TaskStatusResponse,
            crate::controllers::folders::FolderResponse,
            crate::controllers::folders::CreateFolderRequest,
            crate::controllers::folders::RenameFolderRequest,
            crate::controllers::folders::AssignFolderRequest,
            crate::controllers::admin::FixDriftResponse,
            crate::controllers::admin::FaviconTaskResponse,
            crate::controllers::admin::FetchNowResponse,
            crate::controllers::admin::AdminFeedResponse,
            crate::controllers::admin::AdminUpdateFeedRequest,
            kaleido::glass::aggregator::NamedStat,
        )
    ),
    tags(
        (name = "admin", description = "Admin-only endpoints"),
        (name = "auth", description = "Authentication and user management"),
        (name = "feeds", description = "RSS feed management"),
        (name = "flags", description = "Feature flags"),
        (name = "oauth", description = "OAuth authentication")
    ),
    modifiers(&SecurityAddon)
)]
pub struct ApiDoc;
