/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/admin/feature-flags": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all feature flags */
    get: operations["list_flags"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/feature-flags/{key}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Update a single feature flag */
    post: operations["update_flag"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/feeds": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all feeds (admin view) */
    get: operations["admin_list_feeds"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/feeds/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update a feed's fetch interval and enabled/disabled state. */
    put: operations["update_feed"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/feeds/{id}/fetch-history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List fetch history for a feed (admin view) */
    get: operations["admin_list_feed_fetch_history"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/feeds/{id}/fetch-now": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Enqueue an immediate one-off fetch for a specific feed (admin only). */
    post: operations["admin_fetch_feed_now"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/metrics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get glass-managed system metrics (auth, background tasks, etc.)
     * @description Glass automatically expands this response as new subsystems are added.
     */
    get: operations["admin_get_metrics"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/metrics/app": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get RSS-specific app metrics. */
    get: operations["admin_app_metrics"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/tasks/fetch-missing-favicons": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Enqueue a background task to fetch favicons for all feeds that have never had one fetched.
     * @description The worker deduplicates by marking `favicon_fetched_at` before starting each fetch,
     *     so running this multiple times is safe — subsequent enqueues will simply find no work.
     */
    post: operations["fetch_missing_favicons"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/tasks/fix-unread-drift": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Recalculate unread_count for all user_feed subscriptions from ground truth.
     * @description This corrects drift that can accumulate when articles are viewed after a bulk
     *     mark-all-read, causing spurious decrements that undercount genuinely new articles.
     */
    post: operations["fix_unread_drift"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/articles/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single article by ID */
    get: operations["get_article"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/articles/{id}/read": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Mark an article as read for the current user */
    put: operations["mark_article_read"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/articles/{id}/save": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Toggle saved state for an article (save if unsaved, unsave if saved) */
    put: operations["toggle_save_article"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/current": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["current"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/forgot": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["forgot_password"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["logout"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/resend-confirmation": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["resend_confirmation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/reset": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["reset_password"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/verify/{token}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["verify_email"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/feature-flags": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Public endpoint returning all feature flags (safe subset) for clients. */
    get: operations["public_flags"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/feeds": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the current user's subscribed feeds */
    get: operations["list_feeds"];
    put?: never;
    /** Subscribe to a feed by URL (creates the feed if it doesn't exist yet) */
    post: operations["create_feed"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/feeds/reorder": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update sort order for the current user's feed subscriptions */
    put: operations["reorder_feeds"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/feeds/tasks/{task_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the status of a background task (e.g. feed verification) */
    get: operations["get_task_status"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/feeds/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Unsubscribe the current user from a feed */
    delete: operations["unsubscribe_feed"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/feeds/{id}/articles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List articles for a feed */
    get: operations["list_articles"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/feeds/{id}/fetch-history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List fetch history for a feed */
    get: operations["list_fetch_history"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/feeds/{id}/folder": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Assign (or unassign) a feed to a folder */
    put: operations["assign_feed_to_folder"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/feeds/{id}/name": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Set a custom display name for a feed subscription (persisted on user_feeds) */
    put: operations["rename_feed"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/feeds/{id}/view": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Set the article layout mode for a feed subscription */
    put: operations["update_feed_view"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/feeds/{id}/read": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Mark all articles in a feed as read for the current user */
    put: operations["mark_feed_read"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/folders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all folders for the current user */
    get: operations["list_folders"];
    put?: never;
    /** Create a new folder */
    post: operations["create_folder"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/folders/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete a folder (feeds in the folder become unassigned) */
    delete: operations["delete_folder"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/folders/{id}/articles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List articles across all feeds in a folder */
    get: operations["list_folder_articles"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/folders/{id}/name": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Rename a folder */
    put: operations["rename_folder"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/folders/{id}/view": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Set the article layout mode for a folder */
    put: operations["update_folder_view"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oauth/{provider}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Initiate provider OAuth flow - redirect user to provider login */
    get: operations["oauth_authorize"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oauth/{provider}/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Handle OAuth callback for generic provider */
    get: operations["oauth_callback"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AdminFeedResponse: {
      /** Format: int64 */
      article_count: number;
      /** Format: date-time */
      created_at: string;
      enabled: boolean;
      /** Format: int32 */
      fetch_interval_minutes: number;
      /** Format: int32 */
      id: number;
      /** Format: date-time */
      last_fetched_at?: string | null;
      name?: string | null;
      /** Format: date-time */
      next_fetch_at?: string | null;
      /** Format: date-time */
      updated_at: string;
      url: string;
      /** Format: date-time */
      verified_at?: string | null;
    };
    AdminUpdateFeedRequest: {
      enabled?: boolean | null;
      /** Format: int32 */
      fetch_interval_minutes?: number | null;
    };
    ArticleResponse: {
      content?: string | null;
      /** Format: date-time */
      created_at: string;
      description?: string | null;
      /** Format: int32 */
      feed_id: number;
      guid?: string | null;
      /** Format: int32 */
      id: number;
      image_url?: string | null;
      preview?: string | null;
      author?: string | null;
      /** Format: date-time */
      read_at?: string | null;
      /** Format: date-time */
      saved_at?: string | null;
      title?: string | null;
      /** Format: date-time */
      updated_at: string;
      url: string;
    };
    AssignFolderRequest: {
      /**
       * Format: int32
       * @description Folder ID to assign, or null to remove from any folder
       */
      folder_id?: number | null;
    };
    CreateFeedRequest: {
      name?: string | null;
      url: string;
    };
    /** @description Response returned when a new feed subscription is created. */
    CreateFeedResponse: {
      feed: components["schemas"]["FeedResponse"];
      /**
       * @description Background task ID for the feed verification job.
       *     Poll `GET /feeds/tasks/{task_id}` to track verification progress.
       *     `None` when subscribing to an already-verified feed.
       */
      task_id?: string | null;
    };
    CreateFolderRequest: {
      name: string;
    };
    FaviconTaskResponse: {
      message: string;
      task_id: string;
    };
    FeatureFlagResponse: {
      description?: string | null;
      enabled: boolean;
      feature_key: string;
    };
    FeedResponse: {
      /** Format: date-time */
      created_at: string;
      /** @description API path to the feed's favicon (e.g. /api/favicons/feed_1.ico), or null if unavailable */
      favicon_url?: string | null;
      /**
       * Format: int32
       * @description Folder this feed belongs to, or null
       */
      folder_id?: number | null;
      /** Format: int32 */
      id: number;
      /**
       * Format: date-time
       * @description When the feed was last fetched by the worker
       */
      last_fetched_at?: string | null;
      /**
       * Format: date-time
       * @description When the user last marked all articles in this feed as read
       */
      last_read_at?: string | null;
      /** @description Display name: user's override if set, otherwise the feed's own title. */
      name?: string | null;
      /**
       * Format: int32
       * @description User-defined sort order for drag-and-drop ordering
       */
      sort_order: number;
      /**
       * Format: date-time
       * @description When the current user subscribed to this feed
       */
      subscribed_at: string;
      /**
       * Format: int64
       * @description Number of unread articles (articles created after last_read_at, or all if never read)
       */
      unread_count: number;
      /** Format: date-time */
      updated_at: string;
      url: string;
      /** Format: date-time */
      verified_at?: string | null;
      /** @description Article layout mode: list | cards | magazine */
      view_mode: string;
      /** @description Whether to show only unread articles by default */
      only_unread: boolean;
    };
    FetchHistoryResponse: {
      /** Format: int32 */
      article_count?: number | null;
      /** Format: int64 */
      content_length?: number | null;
      error_message?: string | null;
      /** Format: int32 */
      feed_id: number;
      /** Format: date-time */
      fetched_at: string;
      /** Format: int32 */
      id: number;
      /** Format: int32 */
      status_code?: number | null;
    };
    FetchNowResponse: {
      message: string;
      task_id: string;
    };
    FixDriftResponse: {
      message: string;
      /**
       * Format: int64
       * @description Number of user_feed rows whose unread_count was recalculated
       */
      rows_updated: number;
    };
    FolderResponse: {
      /** Format: date-time */
      created_at: string;
      /** Format: int32 */
      id: number;
      name: string;
      /** Format: int32 */
      sort_order: number;
      /**
       * Format: int64
       * @description Total unread article count across all feeds in this folder
       */
      unread_count: number;
      view_mode: string;
      /** @description Whether to show only unread articles by default */
      only_unread: boolean;
      /** Format: date-time */
      updated_at: string;
    };
    ForgotPasswordRequest: {
      email: string;
    };
    LoginRequest: {
      email: string;
      password: string;
    };
    MessageResponse: {
      message: string;
    };
    /**
     * @description A named, displayable metric with a machine-readable key and human-readable label.
     *     Used in sectioned admin metrics responses so the UI can map keys to icons/links.
     */
    NamedStat: {
      /** @description Short time-range description, e.g. "last 30 days". */
      desc: string;
      error?: string | null;
      /** @description Machine-readable identifier — used by the UI to look up icons and links. */
      key: string;
      /** @description Human-readable display label. */
      label: string;
      /** Format: int64 */
      value: number;
    };
    /** @description Standard paginated response wrapper */
    PaginatedResponse_ArticleResponse: {
      /** @description Recordset */
      data: {
        content?: string | null;
        /** Format: date-time */
        created_at: string;
        description?: string | null;
        /** Format: int32 */
        feed_id: number;
        guid?: string | null;
        /** Format: int32 */
        id: number;
        image_url?: string | null;
        preview?: string | null;
        /** Format: date-time */
        read_at?: string | null;
        /** Format: date-time */
        saved_at?: string | null;
        title?: string | null;
        /** Format: date-time */
        updated_at: string;
        url: string;
      }[];
      /** @description Pagination metadata */
      metadata: components["schemas"]["PaginationMetadata"];
    };
    /** @description Standard paginated response wrapper */
    PaginatedResponse_FeatureFlagResponse: {
      /** @description Recordset */
      data: {
        description?: string | null;
        enabled: boolean;
        feature_key: string;
      }[];
      /** @description Pagination metadata */
      metadata: components["schemas"]["PaginationMetadata"];
    };
    /** @description Standard paginated response wrapper */
    PaginatedResponse_FetchHistoryResponse: {
      /** @description Recordset */
      data: {
        /** Format: int32 */
        article_count?: number | null;
        /** Format: int64 */
        content_length?: number | null;
        error_message?: string | null;
        /** Format: int32 */
        feed_id: number;
        /** Format: date-time */
        fetched_at: string;
        /** Format: int32 */
        id: number;
        /** Format: int32 */
        status_code?: number | null;
      }[];
      /** @description Pagination metadata */
      metadata: components["schemas"]["PaginationMetadata"];
    };
    /** @description Standard paginated response wrapper */
    PaginatedResponse_PublicFlagResponse: {
      /** @description Recordset */
      data: {
        enabled: boolean;
        feature_key: string;
      }[];
      /** @description Pagination metadata */
      metadata: components["schemas"]["PaginationMetadata"];
    };
    /** @description Metadata about the pagination state */
    PaginationMetadata: {
      /**
       * Format: int64
       * @description Current page number
       */
      page: number;
      /**
       * Format: int64
       * @description Number of items per page
       */
      per_page: number;
      /**
       * Format: int64
       * @description Total number of items available
       */
      total: number;
      /**
       * Format: int64
       * @description Total number of pages available
       */
      total_pages: number;
    };
    /** @description Standard pagination query parameters */
    PaginationParams: {
      /**
       * Format: int64
       * @description Page number (1-based)
       */
      page?: number;
      /**
       * Format: int64
       * @description Number of items per page
       */
      per_page?: number;
    };
    PublicFlagResponse: {
      enabled: boolean;
      feature_key: string;
    };
    RegisterRequest: {
      email: string;
      name: string;
      password: string;
    };
    RegisterResponse: {
      pid: string;
    };
    RenameFolderRequest: {
      name: string;
    };
    UpdateFolderViewRequest: {
      view_mode: string;
      /** @description Whether to show only unread articles by default. Omit to leave unchanged. */
      only_unread?: boolean | null;
    };
    ReorderFeedItem: {
      /** Format: int32 */
      feed_id: number;
      /** Format: int32 */
      sort_order: number;
    };
    ResendConfirmationRequest: {
      email: string;
    };
    ResetPasswordRequest: {
      password: string;
      token: string;
    };
    /**
     * @description System-wide metrics automatically aggregated from all glass subsystems.
     *
     *     Add new subsystem fields here (and populate them in `collect`) when new
     *     system-level metric categories are added to glass. Consuming controllers
     *     embed this via `#[serde(flatten)]` so new sections appear in the JSON
     *     response without any controller changes.
     */
    SystemMetrics: {
      auth: components["schemas"]["NamedStat"][];
      background_tasks: components["schemas"]["NamedStat"][];
    };
    /** @description Status of a background task (e.g. feed verification). */
    TaskStatusResponse: {
      /** Format: int32 */
      attempts: number;
      error?: string | null;
      id: string;
      /** Format: int32 */
      max_attempts: number;
      /** @description One of: pending, processing, completed, failed */
      status: string;
    };
    UpdateFeedNameRequest: {
      /** @description New display name. Pass `null` to clear the override and fall back to the feed's default name. */
      name?: string | null;
    };
    UpdateFeedViewRequest: {
      /** @description Layout mode for this feed's articles. One of: list, cards, magazine. */
      view_mode: string;
      /** @description Whether to show only unread articles by default. Omit to leave unchanged. */
      only_unread?: boolean | null;
    };
    UpdateFlagRequest: {
      enabled: boolean;
    };
    UserResponse: {
      email: string;
      is_admin: boolean;
      name: string;
      pid: string;
      verified: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_flags: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of feature flags */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedResponse_FeatureFlagResponse"];
        };
      };
    };
  };
  update_flag: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Feature flag key */
        key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateFlagRequest"];
      };
    };
    responses: {
      /** @description Flag updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeatureFlagResponse"];
        };
      };
    };
  };
  admin_list_feeds: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of all feeds */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminFeedResponse"][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_feed: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminUpdateFeedRequest"];
      };
    };
    responses: {
      /** @description Feed updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminFeedResponse"];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Feed not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  admin_list_feed_fetch_history: {
    parameters: {
      query?: {
        /** @description Page number (1-based) */
        page?: number;
        /** @description Number of items per page */
        per_page?: number;
      };
      header?: never;
      path: {
        /** @description Feed ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Fetch history */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedResponse_FetchHistoryResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Feed not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  admin_fetch_feed_now: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Feed ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Fetch task enqueued */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FetchNowResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Feed not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  admin_get_metrics: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Glass system metrics */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SystemMetrics"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  admin_app_metrics: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description RSS app metrics */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NamedStat"][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  fetch_missing_favicons: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Task enqueued */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FaviconTaskResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  fix_unread_drift: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Drift corrected */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FixDriftResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_article: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Article ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Article */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArticleResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Article not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  mark_article_read: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Article ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Article marked as read */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Article not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  toggle_save_article: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Article ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Saved state toggled */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Article not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  current: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current user info */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  forgot_password: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ForgotPasswordRequest"];
      };
    };
    responses: {
      /** @description Password reset email sent if user exists */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Login successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Too many login attempts */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logout successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Optional refresh token in body or cookie */
    requestBody: {
      content: {
        "application/json": string;
      };
    };
    responses: {
      /** @description Token refreshed successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid refresh token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description User registered successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RegisterResponse"];
        };
      };
      /** @description Validation error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  resend_confirmation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResendConfirmationRequest"];
      };
    };
    responses: {
      /** @description Confirmation email sent */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  reset_password: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordRequest"];
      };
    };
    responses: {
      /** @description Password reset successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid or expired token */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  verify_email: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Email verification token */
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Email verified successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Invalid or expired token */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  public_flags: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of feature flags */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedResponse_PublicFlagResponse"];
        };
      };
    };
  };
  list_feeds: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List user feeds */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeedResponse"][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  create_feed: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateFeedRequest"];
      };
    };
    responses: {
      /** @description Subscribed to feed */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateFeedResponse"];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  reorder_feeds: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReorderFeedItem"][];
      };
    };
    responses: {
      /** @description Sort order updated */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_task_status: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Background task ID */
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Task status */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskStatusResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Task not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  unsubscribe_feed: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Feed ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Unsubscribed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_articles: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Feed ID */
        id: number;
        /** @description Page number (1-based) */
        page: number;
        /** @description Number of items per page */
        per_page: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List feed articles */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedResponse_ArticleResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Feed not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_fetch_history: {
    parameters: {
      query?: {
        /** @description Page number (1-based) */
        page?: number;
        /** @description Number of items per page */
        per_page?: number;
      };
      header?: never;
      path: {
        /** @description Feed ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Fetch history */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedResponse_FetchHistoryResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Feed not found or not subscribed */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  assign_feed_to_folder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Feed ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssignFolderRequest"];
      };
    };
    responses: {
      /** @description Feed folder updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Feed subscription not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  rename_feed: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Feed ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateFeedNameRequest"];
      };
    };
    responses: {
      /** @description Name updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeedResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Feed not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_feed_view: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Feed ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateFeedViewRequest"];
      };
    };
    responses: {
      /** @description View mode updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeedResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Feed not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  mark_feed_read: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Feed ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Feed marked as read */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Subscription not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_folders: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List folders */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FolderResponse"][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  create_folder: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateFolderRequest"];
      };
    };
    responses: {
      /** @description Folder created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FolderResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_folder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Folder ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Folder deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Folder not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_folder_articles: {
    parameters: {
      query?: {
        /** @description Page number (1-based) */
        page?: number;
        /** @description Number of items per page */
        per_page?: number;
      };
      header?: never;
      path: {
        /** @description Folder ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Folder articles */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedResponse_ArticleResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Folder not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  rename_folder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Folder ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RenameFolderRequest"];
      };
    };
    responses: {
      /** @description Folder renamed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FolderResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Folder not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_folder_view: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Folder ID */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateFolderViewRequest"];
      };
    };
    responses: {
      /** @description Folder view mode updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FolderResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Folder not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  oauth_authorize: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description OAuth provider name */
        provider: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirect to provider */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  oauth_callback: {
    parameters: {
      query: {
        code: string;
        state?: string | null;
      };
      header?: never;
      path: {
        /** @description OAuth provider name */
        provider: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirect to frontend */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
