when:
  - event: push
    branch:
      exclude: main

steps:
  - name: clone-kaleido
    image: alpine/git
    when:
      - event: push
        path:
          include:
            - "api/**"
            - "worker/**"
            - "migration/**"
            - "Cargo.toml"
            - "Cargo.lock"
            - ".woodpecker/clone-kaleido.sh"
            - ".woodpecker/test-rust.sh"
    commands:
      - sh .woodpecker/clone-kaleido.sh

  - name: test-rust
    image: rust:1-bookworm
    depends_on: [clone-kaleido]
    when:
      - event: push
        path:
          include:
            - "api/**"
            - "worker/**"
            - "migration/**"
            - "Cargo.toml"
            - "Cargo.lock"
            - ".woodpecker/clone-kaleido.sh"
            - ".woodpecker/test-rust.sh"
    environment:
      TEST_MODE: "1"
    commands:
      - sh .woodpecker/test-rust.sh

  - name: test-ui
    image: node:25-alpine
    when:
      - event: push
        path:
          include:
            - "ui-next/**"
            - ".woodpecker/test-ui.sh"
    commands:
      - sh .woodpecker/test-ui.sh
